[package]
name = "master-server-types"
version = "0.1.0"
edition = "2024"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
publish = false
license = "Zlib"

[dependencies]
arrayvec = { version = "=0.5.2", features = ["serde"] }
csv = "1.4.0"
http = "=0.2.12"
ipnet = { version = "2.11.0", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = [
  "float_roundtrip",
  "preserve_order",
  "raw_value",
] }
url = { version = "2.5.7", features = ["serde"] }

serde_with = "3.15.1"
