[package]
name = "prediction-timer"
version = "0.1.0"
edition = "2024"

[dependencies]
math = { path = "../../lib/math" }

tracing = { version = "0.1.41", default-features = false, features = [
  "attributes",
] }

[dev-dependencies]
rgb = "0.8.52"
textplots = "0.8.7"
