[package]
name = "master-server"
version = "0.1.0"
edition = "2024"
authors = ["heinrich5991 <heinrich5991@gmail.com>"]
publish = false
license = "Zlib"

[dependencies]
master-server-types = { path = "../../game/master-server-types" }

arrayvec = { version = "=0.5.2", features = ["serde"] }
base64 = "=0.13.1"
bytes = "1.10.1"
clap = { version = "=2.34.0", default-features = false, features = [
  "suggestions",
  "wrap_help",
] }
env_logger = "0.11.8"
headers = "=0.3.9"
hex = "0.4.3"
log = "0.4.28"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = [
  "float_roundtrip",
  "preserve_order",
  "raw_value",
] }
sha2 = "0.10.9"
tokio = { version = "1.48.0", features = ["macros", "rt", "rt-multi-thread"] }
tokio-stream = { version = "0.1.17", features = ["net"] }
warp = { version = "0.3.7", default-features = false }
