use libtw2_gamenet_ddnet::msg::game::{SvTuneParams, TuneParam};
use vanilla::collision::Tunings;

pub fn translate(t: &Tunings) -> SvTuneParams {
    SvTuneParams {
        ground_control_speed: TuneParam((t.ground_control_speed * 100.0).round() as i32),
        ground_control_accel: TuneParam((t.ground_control_accel * 100.0).round() as i32),
        ground_friction: TuneParam((t.ground_friction * 100.0).round() as i32),
        ground_jump_impulse: TuneParam((t.ground_jump_impulse * 100.0).round() as i32),
        air_jump_impulse: TuneParam((t.air_jump_impulse * 100.0).round() as i32),
        air_control_speed: TuneParam((t.air_control_speed * 100.0).round() as i32),
        air_control_accel: TuneParam((t.air_control_accel * 100.0).round() as i32),
        air_friction: TuneParam((t.air_friction * 100.0).round() as i32),
        hook_length: TuneParam((t.hook_length * 100.0).round() as i32),
        hook_fire_speed: TuneParam((t.hook_fire_speed * 100.0).round() as i32),
        hook_drag_accel: TuneParam((t.hook_drag_accel * 100.0).round() as i32),
        hook_drag_speed: TuneParam((t.hook_drag_speed * 100.0).round() as i32),
        gravity: TuneParam((t.gravity * 100.0).round() as i32),
        velramp_start: TuneParam((t.velramp_start * 100.0).round() as i32),
        velramp_range: TuneParam((t.velramp_range * 100.0).round() as i32),
        velramp_curvature: TuneParam((t.velramp_curvature * 100.0).round() as i32),
        gun_curvature: TuneParam((t.gun_curvature * 100.0).round() as i32),
        gun_speed: TuneParam((t.gun_speed * 100.0).round() as i32),
        gun_lifetime: TuneParam((t.gun_lifetime * 100.0).round() as i32),
        shotgun_curvature: TuneParam((t.shotgun_curvature * 100.0).round() as i32),
        shotgun_speed: TuneParam((t.shotgun_speed * 100.0).round() as i32),
        shotgun_speeddiff: TuneParam((t.shotgun_speeddiff * 100.0).round() as i32),
        shotgun_lifetime: TuneParam((t.shotgun_lifetime * 100.0).round() as i32),
        grenade_curvature: TuneParam((t.grenade_curvature * 100.0).round() as i32),
        grenade_speed: TuneParam((t.grenade_speed * 100.0).round() as i32),
        grenade_lifetime: TuneParam((t.grenade_lifetime * 100.0).round() as i32),
        laser_reach: TuneParam((t.laser_reach * 100.0).round() as i32),
        laser_bounce_delay: TuneParam((t.laser_bounce_delay * 100.0).round() as i32),
        laser_bounce_num: TuneParam((t.laser_bounce_num * 100.0).round() as i32),
        laser_bounce_cost: TuneParam((t.laser_bounce_cost * 100.0).round() as i32),
        laser_damage: TuneParam((t.laser_damage * 100.0).round() as i32),
        player_collision: TuneParam((t.player_collision * 100.0).round() as i32),
        player_hooking: TuneParam((t.player_hooking * 100.0).round() as i32),
        jetpack_strength: TuneParam((t.jetpack_strength * 100.0).round() as i32),
        shotgun_strength: TuneParam((t.shotgun_strength * 100.0).round() as i32),
        explosion_strength: TuneParam((t.explosion_strength * 100.0).round() as i32),
        hammer_strength: TuneParam((t.hammer_strength * 100.0).round() as i32),
        hook_duration: TuneParam((t.hook_duration * 100.0).round() as i32),
        hammer_fire_delay: TuneParam((t.hammer_fire_delay * 100.0).round() as i32),
        gun_fire_delay: TuneParam((t.gun_fire_delay * 100.0).round() as i32),
        shotgun_fire_delay: TuneParam((t.shotgun_fire_delay * 100.0).round() as i32),
        grenade_fire_delay: TuneParam((t.grenade_fire_delay * 100.0).round() as i32),
        laser_fire_delay: TuneParam((t.laser_fire_delay * 100.0).round() as i32),
        ninja_fire_delay: TuneParam((t.ninja_fire_delay * 100.0).round() as i32),
        hammer_hit_fire_delay: TuneParam((t.hammer_hit_fire_delay * 100.0).round() as i32),
        ground_elasticity_x: TuneParam(0),
        ground_elasticity_y: TuneParam(0),
    }
}
