name: Build

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  pull_request:
  merge_group:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
        - os: ubuntu-latest
          features-debug: "bundled_data_dir,ffmpeg,microphone"
          features: "bundled_data_dir,ffmpeg,microphone,auto_updater"
          bin: ddnet-rs
          server-bin: server
          x264-src: x264
          x264-build: x264-build
          x264-cache-path: x264-build
          x264-lib-dir: /usr/local/lib
          x264-include-dir: /usr/local/include
        - os: macOS-latest
          features-debug: "bundled_data_dir,ffmpeg,microphone"
          features: "bundled_data_dir,ffmpeg,microphone,auto_updater"
          bin: ddnet-rs
          server-bin: server
          x264-src: x264
          x264-build: x264-build
          x264-cache-path: x264-build
          x264-lib-dir: /usr/local/lib
          x264-include-dir: /usr/local/include
        - os: windows-latest
          # ffmpeg takes years on win
          features-debug: "bundled_data_dir,microphone"
          features: "bundled_data_dir,ffmpeg,microphone,auto_updater"
          bin: ddnet-rs.exe
          server-bin: server.exe
          x264-src: /c/x264
          x264-build: /c/build-x264
          x264-cache-path: 'C:\build-x264'
          x264-lib-dir: /mingw64/lib
          x264-include-dir: /mingw64/include
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.os == 'windows-latest' && 'msys2 {0}' || 'bash {0}' }}
    steps:
    - name: Prepare Windows (msys2)
      uses: msys2/setup-msys2@v2
      if: contains(matrix.os, 'windows')
      with:
        update: true
        msystem: MINGW64
  
    - name: Configure Windows Path for msys2
      shell: powershell {0}
      if: contains(matrix.os, 'windows')
      run: |
        $env:PATH = "${{ steps.msys2.outputs.msys2-location }}/usr/bin;" + [System.Environment]::GetEnvironmentVariable("Path", "User")
        [System.Environment]::SetEnvironmentVariable("Path", $env:PATH, "User")

    - name: Configure rustup for msys2
      if: contains(matrix.os, 'windows')
      env:
        MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
      run: |
        export PATH="/c/users/$(whoami)/.cargo/bin:$PATH"
        echo -e "export PATH=\"/c/users/$(whoami)/.cargo/bin:\$PATH\"\n" >> ~/.bash_profile
        echo -e "export MINGW_ARCH=mingw64\n" >> ~/.bash_profile
        # Clearify the libclang path
        echo "export LIBCLANG_PATH=${MSYS2_LOCATION}/mingw64/bin" >> ~/.bash_profile
        echo "export BINDGEN_EXTRA_CLANG_ARGS=--target=x86_64-w64-windows-gnu -isystem${MSYS2_LOCATION}/mingw64/include" >> ~/.bash_profile

    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: |
        rustup toolchain install stable --profile minimal
        rustup component add clippy

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt update -y
        sudo apt install rustc cargo gcc libwayland-dev libasound2-dev nasm -y
        # for ffmpeg, DON'T install libx264
        sudo apt install -y clang libavcodec-dev libavformat-dev libavutil-dev
        echo "LIBOPUS_NO_PKG=1" >> "$GITHUB_ENV"
        echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig" >> "$GITHUB_ENV"

    - name: Prepare macOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew update || true
        brew install pkg-config autoconf automake || true
        # for ffmpeg, DON'T install libx264
        brew install ffmpeg || true
        # for building molten vk
        brew install python-setuptools || true
        echo "LIBOPUS_NO_PKG=1" >> "$GITHUB_ENV"
        echo "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/share/pkgconfig" >> "$GITHUB_ENV"

    - name: Prepare msys dependencies
      if: contains(matrix.os, 'windows')
      run: |
        # important detail: mingw-w64-x86_64-libx264 is installed for the package config files!
        pacman --noconfirm -S git make mingw-w64-x86_64-libx264 mingw-w64-x86_64-toolchain mingw-w64-x86_64-clang mingw-w64-x86_64-gcc mingw-w64-x86_64-nasm mingw-w64-x86_64-opus

    - name: Prepare msys
      if: contains(matrix.os, 'windows')
      run: |
        rustup target add x86_64-pc-windows-gnu
        rustup update stable
        rustup set default-host x86_64-pc-windows-gnu
        rustup default stable-x86_64-pc-windows-gnu

    - name: Setup cache for x264
      uses: actions/cache@v4
      id: x264-cache
      with:
        path: ${{ matrix.x264-cache-path }}
        key: ${{ runner.os }}-x264-0480cb05fa188d37ae87e8f4fd8f1aea3711f7ee

    - name: Build static x264
      if: steps.x264-cache.outputs.cache-hit != 'true'
      run: |
        set -e
        SRC="${{ matrix.x264-src }}"
        BUILD="${{ matrix.x264-build }}"
        if [ "$RUNNER_OS" != "Windows" ]; then
          SRC="$GITHUB_WORKSPACE/$SRC"
          BUILD="$GITHUB_WORKSPACE/$BUILD"
        fi
        git clone --no-checkout https://code.videolan.org/videolan/x264.git "$SRC"
        cd "$SRC"
        git fetch origin 0480cb05fa188d37ae87e8f4fd8f1aea3711f7ee --depth 1
        git checkout 0480cb05fa188d37ae87e8f4fd8f1aea3711f7ee
        mkdir -p "$BUILD"
        cd "$BUILD"
        "$SRC/configure" --enable-static --enable-pic
        if command -v nproc >/dev/null 2>&1; then
          CORES=$(nproc)
        else
          CORES=$(sysctl -n hw.ncpu)
        fi
        make -j8 libx264.a
        cp "$SRC/x264.h" "$BUILD/x264.h"

    - name: Install x264 artifacts
      run: |
        set -e
        BUILD="${{ matrix.x264-build }}"
        if [ "$RUNNER_OS" != "Windows" ]; then
          BUILD="$GITHUB_WORKSPACE/$BUILD"
        fi
        LIB_DIR="${{ matrix.x264-lib-dir }}"
        INCLUDE_DIR="${{ matrix.x264-include-dir }}"
        if [ "${{ runner.os }}" = "Windows" ]; then
          rm -f "$LIB_DIR/libx264.dll.a"
          cp "$BUILD/libx264.a" "$LIB_DIR/libx264.a"
          cp "$BUILD/x264.h" "$INCLUDE_DIR/x264.h"
          cp "$BUILD/x264_config.h" "$INCLUDE_DIR/x264_config.h"
        else
          sudo mkdir -p "$LIB_DIR" "$INCLUDE_DIR"
          sudo cp "$BUILD/libx264.a" "$LIB_DIR/libx264.a"
          sudo cp "$BUILD/x264.h" "$INCLUDE_DIR/x264.h"
          sudo cp "$BUILD/x264_config.h" "$INCLUDE_DIR/x264_config.h"
          sudo mkdir -p /usr/local/lib/pkgconfig
          sudo cp "$BUILD/x264.pc" /usr/local/lib/pkgconfig/x264.pc
        fi

    - uses: Swatinem/rust-cache@v2

    - name: Build debug
      # disable windows for now, since it's the slowest build
      if: contains(matrix.os, 'windows') == false
      run: cargo build --verbose --features ${{ matrix.features-debug }}

    - name: Build release
      run: cargo build --release --verbose --features ${{ matrix.features }}

    - name: Build server release
      run: cargo build -p server --release --verbose --features bundled_data_dir

    - name: Clippy release
      if: contains(matrix.os, 'ubuntu')
      run: |
        cargo clippy --release --verbose --features ${{ matrix.features }} -- -D warnings
        cargo clippy -p server --release --verbose --features bundled_data_dir -- -D warnings

    - name: Compute lowercase name parts
      id: nameparts
      run: |
        set -euo pipefail
        os_lc=$(echo "${{ runner.os }}" | tr '[:upper:]' '[:lower:]')
        arch_lc=$(echo "${{ runner.arch }}" | tr '[:upper:]' '[:lower:]')
        echo "os=$os_lc" >> "$GITHUB_OUTPUT"
        echo "arch=$arch_lc" >> "$GITHUB_OUTPUT"

    - name: Prepare artifacts
      run: |
        mkdir bin-artifacts || true
        mv target/release/${{ matrix.bin }} bin-artifacts
        mv target/release/${{ matrix.server-bin }} bin-artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ddnet-rs-${{ steps.nameparts.outputs.os }}-${{ steps.nameparts.outputs.arch }}
        path: bin-artifacts

    - name: Build release with steam
      run: cargo build --release --verbose --features ${{ matrix.features }},enable_steam

    - name: Prepare artifacts steam
      run: |
        mkdir bin-artifacts || true
        mv target/release/${{ matrix.bin }} bin-artifacts

    - name: Upload Artifacts steam
      uses: actions/upload-artifact@v4
      with:
        name: ddnet-rs-${{ steps.nameparts.outputs.os }}-${{ steps.nameparts.outputs.arch }}-steam
        path: bin-artifacts
